spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tu_basedatos
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
